services:
  ubuntu:
    build:
      context: .
      args:
        SYSTEM_USER: ${SYSTEM_USER}
        SYSTEM_PASSWORD: ${SYSTEM_PASSWORD}
        SYSTEM_HOSTNAME: ${SYSTEM_HOSTNAME}
    container_name: ubuntu-${SYSTEM_USER}
    restart: unless-stopped
    hostname: ${SYSTEM_HOSTNAME}
    tty: true
    stdin_open: true
    ports:
      - "${SSH_PORT}:22"
    volumes:
      - ubuntu_data:/home/${SYSTEM_USER}
    mem_limit: ${MEM_LIMIT}
    mem_swappiness: 0
    memswap_limit: ${MEM_SWAP_LIMIT}
    cpus: ${CPU_LIMIT}

volumes:
  ubuntu_data:
